---

# - name: "install npm"
#   become: true
#   apk:
#     name: ["npm"]
#     state: latest
#     update_cache: yes

# - name: "Install pm2 if not installed"
#   command: npm install pm2 -g
#   args:
#     creates: /usr/local/bin/pm2
#   become: yes

# - name: "upgrade packages."
#   become: true
#   apk:
#     upgrade: "yes"

# - name: "install dependencies."
#   become: true
#   apk:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present
- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .
    
- name: start app
  become: yes
  shell: |
    npm install
    pm2 stop all
    pm2 start npm --name "udapeople-backend" -- run start
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ./src/migrations
    TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    TYPEORM_HOST: database-1-udapeople.ca9isvmkylw2.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: haribou88
    TYPEORM_DATABASE: postgres
    
- name: "Set pm2 start as service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
- name: check pm2 status
  become: yes
  shell: |
    pm2 describe "udapeople-backend"
  register: command_output_npm
- debug: var=command_output_npm.stdout_lines
